name: Build Executables for To-Do App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Create Virtual Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate  # Activate virtual environment (on Unix-based systems)
        venv\Scripts\activate.bat  # For Windows systems

    - name: Upgrade pip and Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller

    - name: Download RAR parts
      run: |
        mkdir -p dist
        curl -L -o dist/dist.part1.rar https://github.com/namant43fg/TODOAPP/raw/main/dist.part1.rar
        curl -L -o dist/dist.part2.rar https://github.com/namant43fg/TODOAPP/raw/main/dist.part2.rar
        curl -L -o dist/dist.part3.rar https://github.com/namant43fg/TODOAPP/raw/main/dist.part3.rar

    - name: Install unrar (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        if [[ "$(uname)" == "Darwin" ]]; then
          brew install unrar || true
        else
          sudo apt-get install -y unrar
        fi

    - name: Extract RAR files
      run: |
        cd dist
        unrar x dist.part1.rar

    - name: Verify extracted file
      run: |
        ls -l dist
        file dist/todo.py

    - name: Build executable for ${{ matrix.os }}
      run: |
        source venv/bin/activate  # Activate virtual environment (on Unix-based systems)
        venv\Scripts\activate.bat  # For Windows systems
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          pyinstaller --onefile --distpath dist/linux dist/todo.py
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          pyinstaller --onefile --distpath dist/macos dist/todo.py
        else
          pyinstaller --onefile --distpath dist/windows dist/todo.py

    - name: Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: todo-${{ matrix.os }}
        path: |
          dist/linux/*
          dist/macos/*
          dist/windows/*
