name: Build and Upload Split Files

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # This job will run on Ubuntu, modify this for other OS types

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Runs on Linux, Windows, and macOS

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust Python version if necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add your dependencies here

    - name: Create Executable (Windows, Linux, macOS)
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          pyinstaller --onefile --distpath dist-linux todo.py
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          pyinstaller --onefile --distpath dist-win todo.py
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          pyinstaller --onefile --distpath dist-mac todo.py
        fi

    - name: Create .rar Archive (split into 3 parts)
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          rar a -v100m dist-linux.rar dist-linux/todo  # Modify if necessary
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          rar a -v100m dist-win.rar dist-win/todo  # Modify if necessary
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          rar a -v100m dist-mac.rar dist-mac/todo  # Modify if necessary
        fi

    - name: Upload the split .rar files
      uses: actions/upload-artifact@v3
      with:
        name: todo-split-files
        path: |
          dist-linux.rar.part1
          dist-linux.rar.part2
          dist-linux.rar.part3
          dist-win.rar.part1
          dist-win.rar.part2
          dist-win.rar.part3
          dist-mac.rar.part1
          dist-mac.rar.part2
          dist-mac.rar.part3
