name: Build Executables

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the version you need (e.g., 3.8, 3.9, etc.)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install additional dependencies (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libgtk-3-0

    - name: Build executable for ${{ runner.os }}
      run: |
        pyinstaller --onefile --windowed todo.py

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable-${{ runner.os }}
        path: dist/todo  # Path to the generated executable
